# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dev', '0001_squashed_0002_auto_20180117_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extends_user',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
