# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-15 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_auto_20180118_0212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='main_board',
        ),
        migrations.AlterModelTable(
            name='extendsuser',
            table='main_extendsuser',
        ),
        migrations.AlterModelTable(
            name='macro',
            table='main_macro',
        ),
        migrations.AlterModelTable(
            name='macrofeelog',
            table='main_macrofeelog',
        ),
        migrations.AlterModelTable(
            name='macrolog',
            table='main_macrolog',
        ),
        migrations.AlterModelTable(
            name='userpage',
            table='main_userpage',
        ),
    ]
