# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_auto_20180615_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='active_yn',
            field=models.BooleanField(default=True),
        ),
    ]
