# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-08 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macro',
            name='auth_date',
        ),
        migrations.RemoveField(
            model_name='macro',
            name='fee',
        ),
    ]
