# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20170108_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='end_yn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
