# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료일'),
        ),
    ]
