# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170211_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='title',
            field=models.CharField(max_length=30, verbose_name='매크로명'),
        ),
    ]
