# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
