# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-16 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170413_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='count',
        ),
    ]
