# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-09 08:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, help_text='필수 항목. 10자 이하. 문자와 숫자만 가능.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+$', '유효한 닉네임을 입력해주세요. 이 항목은 문자와 숫자만 사용 가능합니다.')], verbose_name='닉네임'),
        ),
    ]
