# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macrolog',
            old_name='succeded',
            new_name='succeeded',
        ),
    ]
