# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170509_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
