# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-20 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170511_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendsuser',
            name='nickname_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 20, 8, 25, 12, 259437, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
