# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_extendsuser_nickname_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created'], 'verbose_name_plural': '게시판'},
        ),
    ]
