# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_board_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='display',
            field=models.BooleanField(default=True, verbose_name='표시'),
        ),
        migrations.AddField(
            model_name='board',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='삭제'),
        ),
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(max_length=50, verbose_name='카테고리'),
        ),
    ]
